import re
import os
from typing import Optional

import pdfplumber


# ── Hebrew final-form letters (appear ONLY at end of words) ──────────────────
# If one appears at the START of a line, the line is definitely reversed.
_HEBREW_FINALS = set('ךםןףץ')   # final kaf, mem, nun, pe, tsadi
_HEBREW_RANGE  = ('\u05d0', '\u05ea')  # alef..tav


def fix_hebrew_visual_order(text: str) -> str:
    """
    PDFs generated by older Hebrew software (including חשבשבת) often store text
    in *visual* order — characters are written left-to-right in the file, so the
    whole line reads backwards.  This function detects and reverses those lines.

    Detection rules (applied per line):
    1. Line has ≥ 3 Hebrew characters.
    2. First Hebrew character is a final-form letter (ךםןףץ)  → definitely reversed.
    3. Heuristic: Hebrew ratio > 40% AND line does NOT start with a Hebrew char
       but DOES end with one  → likely reversed.
    """
    return '\n'.join(_fix_line(line) for line in text.split('\n'))


def _fix_line(line: str) -> str:
    stripped = line.strip()
    if not stripped:
        return line

    heb_chars = [c for c in stripped if _HEBREW_RANGE[0] <= c <= _HEBREW_RANGE[1]]
    if len(heb_chars) < 3:
        return line

    first_heb = heb_chars[0]
    last_heb  = heb_chars[-1]

    # Rule 1: final form at the END of the line → correct logical order, no change
    if last_heb in _HEBREW_FINALS:
        return line

    # Rule 2: any Hebrew *word* starts with a final-form letter → definitely reversed.
    # (Final forms ךםןףץ can NEVER appear at the start of a word in correct Hebrew.)
    words = stripped.split()
    for word in words:
        first_heb_in_word = next((c for c in word if _HEBREW_RANGE[0] <= c <= _HEBREW_RANGE[1]), '')
        if first_heb_in_word in _HEBREW_FINALS:
            return line[::-1]

    # Rule 3: heuristic — high Hebrew ratio, doesn't start with Hebrew but ends with it
    heb_ratio  = len(heb_chars) / max(len(stripped.replace(' ', '')), 1)
    starts_heb = _HEBREW_RANGE[0] <= stripped[0]  <= _HEBREW_RANGE[1]
    ends_heb   = _HEBREW_RANGE[0] <= stripped[-1] <= _HEBREW_RANGE[1]

    if heb_ratio > 0.40 and ends_heb and not starts_heb:
        return line[::-1]

    return line


# ── Regex patterns for Hebrew invoices / receipts ────────────────────────────

_DATE_PATTERNS = [
    r"\b\d{1,2}[./]\d{1,2}[./]\d{2,4}\b",
    r"\b\d{4}-\d{2}-\d{2}\b",
]

_AMOUNT_PATTERNS = [
    r'סה["\u05f4]כ\s+לתשלום[:\s]+[\u20aa]?\s*([\d,]+\.?\d*)',
    r'סה["\u05f4]כ\s+כולל\s+מע["\u05f4]מ[:\s]+[\u20aa]?\s*([\d,]+\.?\d*)',
    r'סה["\u05f4]כ[:\s]+[\u20aa]?\s*([\d,]+\.?\d*)',
    r'סכום\s+כולל[:\s]+[\u20aa]?\s*([\d,]+\.?\d*)',
    r'לתשלום[:\s]+[\u20aa]?\s*([\d,]+\.?\d*)',
    r'[\u20aa]\s*([\d,]+\.\d{2})',
]

_DOC_NUMBER_PATTERNS = [
    r'מס[\'׳\u05f3]?\s*חשבונית[:\s#]+(\w+)',
    r'חשבונית\s+מס[\'׳\u05f3]?\s*[:\s#]+(\w+)',
    r'מספר\s+חשבונית[:\s]+(\w+)',
    r'מס[\'׳\u05f3]?\s*קבלה[:\s#]+(\w+)',
    r'מספר\s+קבלה[:\s]+(\w+)',
    r'(?:invoice|receipt)\s*#?\s*:?\s*(\w+)',
    r'#\s*(\d{4,})',
]


class PDFProcessor:
    def extract(self, pdf_path: str) -> dict:
        """Return a dict with: text, date, total_amount, doc_number."""
        text = self._read_text(pdf_path)
        text = fix_hebrew_visual_order(text)
        return {
            "text": text,
            "date": self._extract_date(text),
            "total_amount": self._extract_amount(text),
            "doc_number": self._extract_doc_number(text),
        }

    @staticmethod
    def _read_text(pdf_path: str) -> str:
        text = ""
        try:
            with pdfplumber.open(pdf_path) as pdf:
                for page in pdf.pages:
                    page_text = page.extract_text() or ""
                    text += page_text + "\n"
        except Exception:
            pass
        return text

    @staticmethod
    def _extract_date(text: str) -> str:
        for pattern in _DATE_PATTERNS:
            match = re.search(pattern, text)
            if match:
                return match.group(0)
        return ""

    @staticmethod
    def _extract_amount(text: str) -> float:
        all_matches = []
        for pattern in _AMOUNT_PATTERNS:
            for match in re.finditer(pattern, text, re.IGNORECASE):
                try:
                    val = float(match.group(1).replace(",", ""))
                    all_matches.append(val)
                except (ValueError, IndexError):
                    continue
            if all_matches:
                return max(all_matches)
        return 0.0

    @staticmethod
    def _extract_doc_number(text: str) -> str:
        for pattern in _DOC_NUMBER_PATTERNS:
            match = re.search(pattern, text, re.IGNORECASE)
            if match:
                return match.group(1)
        return ""
